# Generated by Django 4.2.13 on 2026-07-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_teacherassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
    ]
