# Generated by Django 4.2.13 on 2026-07-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
